### ISSUE TITLE
depth not available

### ISSUE THREAD

**Issue by bertcay** [SyrianSpock/realsense_gazebo_plugin#1]
Hi,

I was looking for a Gazebo plugin of realsense and tried this project.

When launching the "demo" here is an output :
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
--> depth topic is not published.
Any ideas ?

Here are the published topic : 
$ rostopic list
/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/realsense/camera/color/image_raw
/realsense/camera/color/image_raw/compressed
/realsense/camera/color/image_raw/compressed/parameter_descriptions
/realsense/camera/color/image_raw/compressed/parameter_updates
/realsense/camera/color/image_raw/compressedDepth
/realsense/camera/color/image_raw/compressedDepth/parameter_descriptions
/realsense/camera/color/image_raw/compressedDepth/parameter_updates
/realsense/camera/color/image_raw/theora
/realsense/camera/color/image_raw/theora/parameter_descriptions
/realsense/camera/color/image_raw/theora/parameter_updates
/realsense/camera/ir/image_raw
/realsense/camera/ir/image_raw/compressed
/realsense/camera/ir/image_raw/compressed/parameter_descriptions
/realsense/camera/ir/image_raw/compressed/parameter_updates
/realsense/camera/ir/image_raw/compressedDepth
/realsense/camera/ir/image_raw/compressedDepth/parameter_descriptions
/realsense/camera/ir/image_raw/compressedDepth/parameter_updates
/realsense/camera/ir/image_raw/theora
/realsense/camera/ir/image_raw/theora/parameter_descriptions
/realsense/camera/ir/image_raw/theora/parameter_updates
/realsense/camera/ir2/image_raw
/realsense/camera/ir2/image_raw/compressed
/realsense/camera/ir2/image_raw/compressed/parameter_descriptions
/realsense/camera/ir2/image_raw/compressed/parameter_updates
/realsense/camera/ir2/image_raw/compressedDepth
/realsense/camera/ir2/image_raw/compressedDepth/parameter_descriptions
/realsense/camera/ir2/image_raw/compressedDepth/parameter_updates
/realsense/camera/ir2/image_raw/theora
/realsense/camera/ir2/image_raw/theora/parameter_descriptions
/realsense/camera/ir2/image_raw/theora/parameter_updates
/rosout
/rosout_agg

Gazebo 7 + ROS kinetics used

Thanks
Bertrand

**Comment by SyrianSpock** [comment]
You are right. Only the RGB image was published over ROS.
faf87332e790cdf078fda2c7a1d4e8f67a05a989 should fix your problem. It should publish the depth image (but no point cloud).
I use Gazebo 7 + ROS indigo, so let me know if that works for you.

**Comment by bertcay** [comment]
Thanks for this quick update :)
By "no point cloud" do you mean that output format differs from the real realsense output ?

**Comment by SyrianSpock** [comment]
If I remember correctly, there are multiple launch files for the realsense, some of them only publish depth image (2D image where the pixel value is depth), while other would publish point clouds.
I haven't touched the project in two months, I will need to check the current state of the sensor driver to verify that the output format is still the same.
