### ISSUE TITLE
Getting this issue when building

### ISSUE THREAD

**Issue by Vuwij** [SyrianSpock/realsense_gazebo_plugin#12]
Ubuntu 16.04 Xenial, AMD64

`/home/vuwij/hummingbird_ws/src/realsense_gazebo_plugin/src/gazebo_ros_realsense.cpp: In member function ‘virtual void gazebo::GazeboRosRealsense::OnNewFrame(gazebo::rendering::CameraPtr, gazebo::transport::PublisherPtr)’:
/home/vuwij/hummingbird_ws/src/realsense_gazebo_plugin/src/gazebo_ros_realsense.cpp:57:44: error: ‘class gazebo::physics::World’ has no member named ‘SimTime’
   common::Time current_time = this->world->SimTime();
`

**Comment by mahty24** [comment]
I am getting the same error.

**Comment by SyrianSpock** [comment]
My last changes updated the repo for ROS melodic and Gazebo 9, so this is expected.
I pushed a branch to keep it working for ROS kinetic with Gazebo 7: [kinetic-devel](https://github.com/SyrianSpock/realsense_gazebo_plugin/tree/kinetic-devel).
