### ISSUE TITLE
RViz & GAZEBO not opening up 

### ISSUE THREAD

**Issue by bluetulip89** [SyrianSpock/realsense_gazebo_plugin#14]
I build the catkin command. Running depth image command  in one terminal and realsense command as mentioned in your Readme. But RViz and GAZEBO doesnt open as you have shown the picture. Help me out to clear this error.

**Comment by bluetulip89** [comment]
I am using Ubuntu 16.04 ROS Kinetic

**Comment by SyrianSpock** [comment]
What is the error message you get?
Also note that you should use [kinetic-devel](https://github.com/SyrianSpock/realsense_gazebo_plugin/tree/kinetic-devel) branch for the package to work on ROS kinetic / Gazebo 7.

**Comment by bluetulip89** [comment]
Has used the same. Ok will post the error what i get in the terminal. Kindly help out.

**Comment by mahty24** [comment]
I am facing the same issue, and it doen't have errors it only has a warnings as follow.
[Wrn] [msgs.cc:1808] Conversion of sensor type[depth] not suppported.

**Comment by SyrianSpock** [comment]
You should launch rviz from another terminal, simply run: 
```
rviz
```

And Gazebo is intentionally started headless (no GUI), so if you want to its UI you need to set 
```xml
<arg name="headless" value="false"/>
<arg name="gui" value="true"/>
```

**Comment by mahty24** [comment]
thank you @SyrianSpock.

**Comment by SyrianSpock** [comment]
Feel free to reopen if you still have this issue
