### ISSUE TITLE
Err:Light [sun] not found. Use topic ~/factory/light to spawn a new light.

### ISSUE THREAD

**Issue by TouchDeeper** [SyrianSpock/realsense_gazebo_plugin#30]
Hi,
platform:ubunut16.04 ros-kinetic gazebo7
I want to run `roslaunch realsense_gazebo_plugin realsense.launch`, error occur:
```
SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)

auto-starting new master
process[master]: started with pid [11032]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4b5b99b8-4ea0-11e9-a4ce-2016b9896a4d
process[rosout-1]: started with pid [11045]
started core service [/rosout]
process[gazebo-2]: started with pid [11049]
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1553478598.640800789]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1553478598.641189456]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.131
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
[ INFO] [1553478599.694139673]: Realsense Gazebo ROS plugin loading.

RealSensePlugin: The realsense_camera plugin is attach to model realsense_camera
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
[Err] [Scene.cc:2927] Light [sun] not found. Use topic ~/factory/light to spawn a new light.
[ INFO] [1553478599.824697864, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1553478599.848389284, 0.044000000]: Physics dynamic reconfigure ready.
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
```
It seems like the duplicate of the [issue](https://github.com/SyrianSpock/realsense_gazebo_plugin/issues/24#issuecomment-432700560)
But I didn't use virtualbox and I test my version of opengl by `glxinfo | grep OpenGL`,
The verison is `OpenGL version string: 4.6.0 NVIDIA 410.48`.
And the environment variable GAZEBO_MODEL_PATH is  `GAZEBO_MODEL_PATH=/home/wang/interRealsense/r200_gazebo_plugin_ws/src/realsense_gazebo_plugin/models:/home/wang/.gazebo/models`. It seems like no problem.
Can you provide some advice? Thanks a lot!

## update
The alternative `roslaunch realsense_gazebo_plugin realsense_urdf.launch` seems work well.

**Comment by SyrianSpock** [comment]
Yes, [realsense.launch](https://github.com/SyrianSpock/realsense_gazebo_plugin/blob/master/launch/realsense.launch) will spawn a world configured in [realsense.world](https://github.com/SyrianSpock/realsense_gazebo_plugin/blob/master/worlds/realsense.world#L4-L6) that spawns a few Gazebo models (including `sun`). To me it looks like you're missing those models, this may help https://gist.github.com/awesomebytes/982166e825aa23ecdaf9acf34fa0a330
