### ISSUE TITLE
No transform from [depth] to [origin]

### ISSUE THREAD

**Issue by TouchDeeper** [SyrianSpock/realsense_gazebo_plugin#31]
Hi,
I test the plugin by
`roslaunch realsense_gazebo_plugin realsense_urdf.launch`
`roslaunch realsense_gazebo_plugin depth_proc.launch`
`rosrun rviz rviz`
Only the transform from color to origin is ok, as you can see from the image below:
![2019-03-26 11-42-22屏幕截图](https://user-images.githubusercontent.com/39310744/54970256-634dcd80-4fbc-11e9-9e82-489922468a44.png)
The tf tree is below:
![2019-03-26 13-08-58屏幕截图](https://user-images.githubusercontent.com/39310744/54972850-618a0700-4fc8-11e9-9614-5dd854ee3152.png)

Is there any bug?
Another question: where does the link origin come from?

**Comment by SyrianSpock** [comment]
Good catch! Indeed the `origin -> color` TF is a "fake TF" published by this https://github.com/SyrianSpock/realsense_gazebo_plugin/blob/master/launch/depth_proc.launch#L26. I just pushed a commit to remove it on master and kinetic-devel branches (https://github.com/SyrianSpock/realsense_gazebo_plugin/commit/b78d243ec8de320099068543eea80ebc50753507). Thanks for reporting.
