### ISSUE TITLE
the topic of /realsense/camera/depth_registered/points publish no message

### ISSUE THREAD

**Issue by TouchDeeper** [SyrianSpock/realsense_gazebo_plugin#32]
Hi,
I test the plugin by
`roslaunch realsense_gazebo_plugin realsense_urdf.launch`
`roslaunch realsense_gazebo_plugin depth_proc.launch`
`rosrun rviz rviz`
But I can't see the point cloud. I echo the topic of /realsense/camera/depth_registered/points publish no message, It tell me there is no message as the image below:
![2019-04-04 09-59-12屏幕截图](https://user-images.githubusercontent.com/39310744/55524668-aeed2f00-56c0-11e9-9fff-1aca00068144.png)

**Comment by SyrianSpock** [comment]
Thanks @TouchDeeper for reporting the issue. I broke it while fixing #25 (forgot to rename the topics in the `depth_proc.launch` file. It's fixed now in 6c3084559f4b8e4a7458d39dfd198dc62aa1c497
