### ISSUE TITLE
Conversion of sensor type[depth] not supported.

### ISSUE THREAD

**Issue by anubhav1772** [SyrianSpock/realsense_gazebo_plugin#43]
Hi, 
I am a newbie in Ros and trying to run `realsense_gazebo_plugin` but getting some warnings. On running following command `roslaunch realsense_gazebo_plugin realsense.launch`, I am getting below warning messages:
```
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call

RealSensePlugin: The rs_camera plugin is attach to model realsense_camera
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[ INFO] [1573849778.403345017, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1573849778.432398530, 0.041000000]: Physics dynamic reconfigure ready.
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/pose/local/info, deleting message. This warning is printed only once.
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
```
I don't have any idea why I am getting above warnings. But, when I ignored these warnings and run following command: `roslaunch realsense_gazebo_plugin depth_proc.launch` and then start rviz and added pointcloud2 display and set topic `/r200/camera/depth_registered/points`, I am not getting output. Could someone please guide me on this? I would really appreciate your help.

**Comment by grafoteka** [comment]
Hello @anubhav1772, could you solve it? 
I'm having the same problem as you.

Thank you

**Comment by anubhav1772** [comment]
Hey @grafoteka ,
Unfortunately, I wasn't able to solve it yet.

**Comment by SyrianSpock** [comment]
Weird. What ROS and Gazebo versions do you use?

**Comment by grafoteka** [comment]
Hi @SyrianSpock, I'm using ROS Kinetic and Gazebo 7.15

**Comment by SyrianSpock** [comment]
Dumb question: @grafoteka are you using the branch `kinetic-devel`?

**Comment by grafoteka** [comment]
Hi @SyrianSpock , dumb questions are always the best ones!

I forgot to specify the kinetic branch when clone the repo. Now is working perfectly!! 

Thank you very much for the repo!!

**Comment by SyrianSpock** [comment]
Please try the same @anubhav1772 and please re-open if it persists

**Comment by SnowCarter** [comment]
I'm sorry, could you please share what you have done? Where should we specify the kinetic branch?

**Comment by HartmannSa** [comment]
Hi, you (@SnowCarter) should specifiy the branch while cloning the repo, e.g with the command:
git clone -b kinetic-devel https://github.com/pal-robotics/realsense_gazebo_plugin.git

I use Gazebo 9.0 and ros-melodic on Ubuntu 18.04.5 LTS and I get the same error 
[msgs.cc:1852] Conversion of sensor type[depth] not supported.

Due to other reasons the solution "downgrading to Gazebo 7 and use ros-kinetic" is not working for me.
Morover I cloned the correct version (in my case melodic-devel).
So is there a solution for this error for Gazebo 9 and ros-melodic?
