### ISSUE TITLE
Kinetic + Gazebo9

### ISSUE THREAD

**Issue by QING-ML** [SyrianSpock/realsense_gazebo_plugin#44]
could this Realsense_plugin rightly run in kinetic + Gazebo 9? now when I run this plugin in Gazebo 9 . There is no rostopic about /realsense

**Comment by SyrianSpock** [comment]
It should I will verify this and report back

**Comment by SyrianSpock** [comment]
@QING-ML are you using the branch `kinetic-devel`?

**Comment by QING-ML** [comment]
Yes i use kinetic devel



---Original---

**Comment by SyrianSpock** [comment]
Ok I will attempt to replicate the bug locally

**Comment by SyrianSpock** [comment]
Note: I only test on ROS Kinetic with Gazebo 7 the officially supported version AFAICT http://gazebosim.org/tutorials/?tut=ros_wrapper_versions

**Comment by SyrianSpock** [comment]
`kinetic-devel` branch should probably be called `gazebo7` instead, so maybe try the `master` branch since you're on Gazebo 9 please ? (https://github.com/SyrianSpock/realsense_gazebo_plugin/commit/57d824fb3ba870252ff9e1841430377dc55a5b4e)

**Comment by SyrianSpock** [comment]
Since https://github.com/SyrianSpock/realsense_gazebo_plugin/commit/5e332862827674874af43844fcfccfe11a76af95 it should work
