### ISSUE TITLE
No link elements found in urdf file

### ISSUE THREAD

**Issue by q8wwe** [SyrianSpock/realsense_gazebo_plugin#48]
I'm using ros kinetic with gazebo 7.16

No link elements found in urdf file
`[ERROR] [1583184299.047995028]: No link elements found in urdf file
[robot_state_publisher-2] process has died [pid 5282, exit code 255, cmd /opt/ros/kinetic/lib/robot_state_publisher/state_publisher __name:=robot_state_publisher __log:=/home/moh/.ros/log/44847174-5ccc-11ea-99f3-b8ca3a911d19/robot_state_publisher-2.log].
log file: /home/moh/.ros/log/44847174-5ccc-11ea-99f3-b8ca3a911d19/robot_state_publisher-2*.log

`

**Comment by SyrianSpock** [comment]
This is weird, which ROS version? Please confirm the bug on latest master

**Comment by felixvd** [comment]
Post your URDF. You might have included the macro without using it.

**Comment by q8wwe** [comment]
it worked after I initialized the object.
