### ISSUE TITLE
can't download realsense model

### ISSUE THREAD

**Issue by arpit15** [SyrianSpock/realsense_gazebo_plugin#5]
I am getting following error while trying to run
`roslaunch realsense_gazebo_plugin realsense.launch`

... logging to /home/arpit/.ros/log/42c1fe42-1d82-11e7-b849-4ccc6a67057c/roslaunch-littleone-14170.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://128.2.7.87:44544/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.20
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)

auto-starting new master
process[master]: started with pid [14182]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 42c1fe42-1d82-11e7-b849-4ccc6a67057c
process[rosout-1]: started with pid [14195]
started core service [/rosout]
process[gazebo-2]: started with pid [14198]
Gazebo multi-robot simulator, version 7.6.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Err] [Plugin.hh:165] Failed to load plugin //home/arpit/ros_wss/catkin_ws/install/lib/libgazebo_ros_paths_plugin.so: libgazebo_common.so.2: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:165] Failed to load plugin //home/arpit/ros_wss/catkin_ws/install/lib/libgazebo_ros_api_plugin.so: libgazebo_common.so.2: cannot open shared object file: No such file or directory
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 128.2.7.87
[Wrn] [ModelDatabase.cc:340] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
[Err] [ModelDatabase.cc:414] Unable to download model[model://realsense_camera]
[Err] [SystemPaths.cc:410] File or path does not exist[""]
Error [parser.cc:689] Unable to find uri[model://realsense_camera]

When I go to [gazebo models](http://models.gazebosim.org/) I can't find any realsense file. Kindly let me know how to get this working.

Thanks

**Comment by SyrianSpock** [comment]
The realsense model is provided in this repo (https://github.com/SyrianSpock/realsense_gazebo_plugin/tree/master/models/realsense_camera).

I notice that when you launch the node, it fails when looking for gazebo libraries, you may have a problem with path settings.
