### ISSUE TITLE
Multiple cameras.

### ISSUE THREAD

**Issue by guylevy84** [SyrianSpock/realsense_gazebo_plugin#8]
Hi, 
How can i work with multiple cameras?

Thanks, Guy.

**Comment by SyrianSpock** [comment]
One way of doing this, is to expose the Gazebo model in URDF to be used by ROS. Then you can have multiple instances of the camera. This is something I might work on in the near future.

**Comment by guylevy84** [comment]
Thanks, i'll try!

**Comment by SyrianSpock** [comment]
Feel free to reopen if using the URDF (now on master) does not solve your problem.
